---
title: Математическое моделирование прикладных задач. Практическая работа №3. Двухшаговый
  итерационный метод градиентного спуска
author: "Юрченков Иван Александрович"
date: "28 02 2022"
output: html_document
---
## Итерационные методы против прямых методов решения СЛАУ

Пусть поставлена задача решения СЛАУ вида:

$$
    A u = f,
$$
где $A$ -- матрица СЛАУ $f$ -- вектор свободных членов. Вектор $u$ -- численные значения неизвестной функции $u(x)$ непрерывной постановки задачи операторного уравнения. 

Решение уравнения такого вида зачастую находится прямыми методами, среди которых Метод Гаусса, Метод Крамера, Метод обратной матрицы, Разложение Холецкого и т.д., которые находят вектор решения за конечное заранее известное колчиество арифметических операций. Такие методы при большом значении $N$ являются очень ресурсоемкими и в случае слабой обусловленности матрицы также крайне неточными в результате ошибок округления. 

В современной вычислительной математике и математическом моделировании при решении задач с высокой степенью дикретизации чаще обращают внимание на итерационные методы решения СЛАУ. Данные методы позволяют решать СЛАУ с заранее заданной точностью за некоторое количество шагов - умножений матрицы на вектор. Подобные методы находят решение за $C \cdot N^2$ арифметических операций по сравнению с $N^3$ операций как у метода Гаусса.

Среди таких методов имеет место метод градиентного спуска. 

## Двухшаговый метод градиентного спуска

Пусть поставлена задача решения СЛАУ вида:

$$
    A u = f,
$$
$$
    A = (a_{ij}); \ \ \ i = {1, 2 \dots, N}; \ \ \ j = {1, 2 \dots, N},
$$
$$
    u = (u_1, u_2, \dots, u_N),\ \ \ f = (f_1, f_2, \dots, f_N),
$$
где $A$ -- матрица СЛАУ с размерностью $N^2$ и $\forall a_{ij} \in A: a_{ij} \in \mathbf{C}, (i, j) = 0, 1, \dots, N-1$ (в общем случае данная матрица порождена исходя из дискретизации физической задачи и является матрицей линейного оператора); $f: \forall f_i \in \mathbf{C}$ -- вектор свободных членов, заданный, прежде всего исходя из дискретизации неоднородной части уравнения $f(x)$ при дискретизации задачи. Вектор $u: \forall u_i \in \mathbf{C}$ -- численные значения неизвестной функции $u(x)$ непрерывной постановки задачи операторного уравнения. 

Тогда итерации метода градиентного спуска определяются исходя из следующих соотношений:

$$
    r_0 = A \cdot u_0 - f,
$$
$$
    u_1 = u_0 - \frac{||A^{*}\cdot r_0||^2}{||A \cdot A^{*}\cdot r_0||^2} \cdot A^{*} \cdot r_0,
$$
$$
    r_k = A\cdot u_k - f,
$$
$$
\begin{pmatrix} ||\Delta r_k||^2 & ||A^{*} \cdot r_k||^2 \\
                ||A^{*} \cdot r_k||^2 & ||A \cdot A^{*} \cdot r_k||^2 \end{pmatrix}
                \cdot \begin{pmatrix} \alpha_k \\ \gamma_k \end{pmatrix} = 
                \begin{pmatrix} 0 \\ ||A^{*} \cdot r_k||^2 \end{pmatrix},
$$
$$
    u_{k+1} = u_{k} - \alpha_k \cdot (u_k - u_{k-1}) - \gamma_k \cdot A^{*}\cdot r_k,
$$
где $u_k = (u_1^k, u_2^k, \dots, u_N^k)$ и $u_{k+1} = (u_1^{k+1}, u_2^{k+1}, \dots, u_N^{k+1})$ -- неизвестный вектор, значение которого мы ищем на итерациях, на $k$-ом и $(k+1)$-ом шаге итерации соответственно ($u_m^l$ обозначает $m$-тая координата итерации вектора $u_l$); $r_k$ -- невязка на соответствующей итерации решения (разница между отображением искомого приближемого вектора на $k$-ом шаге и свободным вектором правой части); $\alpha_k$ и $\gamma_k$ -- нестационарные итерационные параметры, значение которых ищется на каждой итерации в соответствии с СЛАУ $2 \times 2$ выше;$A^{*}$ -- сопряженный оператор, который ищется в виде:
$$
    A^{*} = (\overline{A})^{T} = \overline{a}_{ji}; \ i,j = 0, 1, \dots, N-1.
$$


Норма $$||x|| = \sqrt{(x, x)},$$ что для комплексных величин определено как:

$$
    (x, y) = \sum_{i = 0}^{N - 1} x_i \cdot \overline{y_j}
$$

Критерий останова для итерационного метода выглядит следующим образом:

$$
    \frac{||u_{k+1} - u_k||}{||f||} < \varepsilon,\ \forall \varepsilon \in \mathbf{R} (0, 0.1)
$$

## Рекомендации

1. Вычисление $||A A^{*} r_k||$ лучше производить по операциям справа налево, то есть сначала умножать $A^{*} r_k$, а затем результат умножать слева на оператор $A$, в результате чего, арифметическая сложность вычислений составит $2N^2$, нежели $N^3 + N^2$ при умножении слева направо.

2. Вычисления умножений матриц на вектор при каждой итерации в итерационных методах решения СЛАУ являются самыми ресурсоемкими со сложностью (в худшем случае) пропорциональной $O(N^2)$, в результате чего следует данные операции стараться производить максимально меньшее число раз с сохранением в памяти их результатов для сокращения к минимуму накладных расходов на итерационный метод и приравниванию скорости решения к теоретически заявленной.

3. Подсчёт итераций итерационного метода стоит производить пропорционально самой ресурсоемкой операции при произведении вычислений. В результате чего, итерационные методы сравниваются по количеству умножений матрицы на вектор в результате релизации метода при решении задач.

## Задание

1. В соответствии с заданием №1 реализовать дикретизацию интегрального уравнения Фредгольма 2-го рода с вырожденным ядром на отрезке с произвольным количеством точек коллокации $N$:

$$
    u(x) + \int_0^1 K(x, y) \cdot u(y) dy = f(x),
$$
где $a = 0,\ b=1$ -- границы отрезка области решения задачи.

2. Реализовать на любом языке программирования двухшаговый итерационный метод градиентного спуска и протестировать его на решении задачи №1.

3. При одинаковых значениях $\varepsilon$ сравнить эффективность и качество сходимости итерационных методов: метода простой итерации, градиентного спуска и двухшагового метода градиентного спуска.