---
title: Математическое моделирование прикладных задач. Практическая работа №5. Обобщенный
  метод минимальных невязок. GMRES
author: "Юрченков Иван Александрович"
date: "01 03 2022"
output: html_document
---

## Обобщенный метод минимальных невязок

Пусть поставлена задача решения СЛАУ вида:

$$
    A u = f,
$$
$$
    A = (a_{ij}); \ \ \ i = {1, 2 \dots, N}; \ \ \ j = {1, 2 \dots, N},
$$
$$
    u = (u_1, u_2, \dots, u_N),\ \ \ f = (f_1, f_2, \dots, f_N),
$$
где $A$ -- матрица СЛАУ с размерностью $N^2$ и $\forall a_{ij} \in A: a_{ij} \in \mathbf{C}, (i, j) = 0, 1, \dots, N-1$ (в общем случае данная матрица порождена исходя из дискретизации физической задачи и является матрицей линейного оператора); $f: \forall f_i \in \mathbf{C}$ -- вектор свободных членов, заданный, прежде всего исходя из дискретизации неоднородной части уравнения $f(x)$ при дискретизации задачи. Вектор $u: \forall u_i \in \mathbf{C}$ -- численные значения неизвестной функции $u(x)$ непрерывной постановки задачи операторного уравнения. 




## Рекомендации

1. Вычисления умножений матриц на вектор при каждой итерации в итерационных методах решения СЛАУ являются самыми ресурсоемкими со сложностью (в худшем случае) пропорциональной $O(N^2)$, в результате чего следует данные операции стараться производить максимально меньшее число раз с сохранением в памяти их результатов для сокращения к минимуму накладных расходов на итерационный метод и приравниванию скорости решения к теоретически заявленной.

2. Подсчёт итераций итерационного метода стоит производить пропорционально самой ресурсоемкой операции при произведении вычислений. В результате чего, итерационные методы сравниваются по количеству умножений матрицы на вектор в результате релизации метода при решении задач.


## Задание

1. Задать диагональную матрицу $(a_{ij}) \in A: \forall a_{ij} \in \mathbf{C}$ 

$$
    a_{ij} = \begin{matrix} \alpha_i + i \cdot \beta_i; \ \  i = j; \ i, j = 1, 2, \dots , N \\
                            0; \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ i\ne j; \ i, j = 1, 2, \dots , N  \end{matrix}
$$

и вектор $f$:

$$
    f = i, \ \ i = 1, 2, \dots, N
$$

2. Реализовать на любом языке программирования обобщенный метод простой итерации и протестировать его на решении задачи №1.
